// <auto-generated />
namespace Caron.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_highlight_category_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_highlight_category_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201609111158045_add_highlight_category_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
